alias iTunes="dex ~/Desktop/iTunes.desktop"
alias sl="sl -Flac"
alias save_sreenshots="mv ~/*.png Pictures/Screenshots"
alias ls="lsd"
alias stop_emacs_service="systemctl --user stop emacs.service"
alias start_emacs_service="systemctl --user start emacs.service"
